// https://leetcode.com/problems/find-the-difference/description/

/*
	You are given two strings s and t.
	
	String t is generated by random shuffling string s and then add one more letter at a random position.
	
	Return the letter that was added to t.
	
	 
	
	Example 1:
	
	Input: s = "abcd", t = "abcde"
	Output: "e"
	Explanation: 'e' is the letter that was added.
	Example 2:
	
	Input: s = "", t = "y"
	Output: "y"
	 
	
	Constraints:
	
	0 <= s.length <= 1000
	t.length == s.length + 1
	s and t consist of lowercase English letters.
*/

package com.easy.problems;
import java.util.*;

public class Find_the_Difference {
	public char findTheDifference(String s, String t) {
        String str1 = sort(s);
        String str2 = sort(t);

        for(int i = 0 ; i < str1.length() ; i++){
            if(str1.charAt(i) != str2.charAt(i)){
                return str2.charAt(i);
            }
        }

        return str2.charAt(str1.length());
    }

    String sort(String s){
        char[] arr = s.toCharArray();
        Arrays.sort(arr);
        return new String(arr);
    }
}
